namespace: awx
name: awx
version: 1.0
authors:
  - Wayne Witzel III
  - Ryan Petrello
  - Abhijeet Kasurde
  - Toshio Kuratomi
  - Pilou
  - John Westcott IV
  - Dag Wieers
  - jainnikhil30
  - Adrien Fleury
  - Lee Shakespeare
  - Alicia Cozine
  - John R Barker
  - Andrea Tartaglia
  - Kevin Clark
  - Matt Martz
  - Meecr0b
  - Pierre Roux
  - Pierre-Louis Bonicoli
  - Rick Elrod
  - Samuel Carpentier
  - Sean Cavanaugh
  - Thierry Bouvet
  - Will Thames
  - curry9999
  - jaevans
  - seag-rvc
  - Andrew J Huffman
  - Andrey Klychkov
  - Bill Nottingham
  - Brian Coca
  - Christopher Galtenberg
  - David Medberry
  - David Moreau Simard
  - Dennis Lerch
  - Hideki Saito
  - Hugh Ma
  - James Cassell
  - James Labocki
readme: README.md
